config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def show
    @flat = Flat.find(params[:id])
  end


  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1 class="text-center">All our flats: (<%= Flat.count %>)</h1>

<div class="container d-flex justify-content-center mb-3">
  <%= link_to "Add flat", new_flat_path, :class => "btn btn-dark"  %>
</div>


<div class="main cards d-flex justify-content-around">
  <% @flats.each do |flat| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body d-flex flex-column justify-content-around">
        <div class="title">
          <h5 class="card-title"> <%= flat.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"> <%= flat.address %> </h6>
        </div>
        <p class="card-text"><%= flat.description %></p>
        <div class="info-box d-flex flex-column text-center">
          <div class="info-details d-flex justify-content-between">
            <i class="fas fa-dollar-sign"> <%= flat.price_per_night %></i>
            <i class="fas fa-user-friends"> <%= flat.number_of_guests %> </i>
          </div>
          <!-- <button type="button" class="btn btn-dark mt-3">More info</button> -->
          <%= link_to "More info", flat_path(flat), class: "btn btn-dark mt-3" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1 class="text-center">Add a new flat</h1>

<%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :price_per_night %>
  <%= f.number_field :price_per_night %>
  <%= f.label :number_of_guests %>
  <%= f.number_field :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<h2> <%= @flat.address %></h2>
<p> <%= @flat.description %></p>
<i class="fas fa-dollar-sign"> <%= @flat.price_per_night %></i>
<i class="fas fa-user-friends"> <%= @flat.number_of_guests %> </i>
<%= link_to "Back", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>